---

- name: Install pip modules
  pip:
    name:
      - psutil

- name: Install Generic Applications
  block:
    - apt:
        pkg:
          - fonts-powerline
          - network-manager-openvpn-gnome
          - figlet
          - toilet
          - golang
          - docker.io
    - apt:
        deb: https://github.com/sharkdp/bat/releases/download/v0.12.1/bat-musl_0.12.1_amd64.deb
  

- name: Install and Use Numix Theme
  block:
    - name: Install icon and theme build tools
      apt:
        pkg:
          - numix-icon-theme-circle
          - ruby-sass
          - libglib2.0-dev 
          - libgdk-pixbuf2.0-dev 
          - libxml2-utils
        update_cache: yes
    - name: Download numix theme
      git:
        repo: https://github.com/numixproject/numix-gtk-theme.git
        dest: /tmp/numix
    - name: Build and Install
      make:
        chdir: /tmp/numix
        target: install
    - name: Set theme to numix
      dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Numix'"
    - name: Set icon theme to numix
      dconf: key="/org/gnome/desktop/interface/icon-theme" value="'Numix-Circle'"

- name: Edit Gnome Settings
  block:
    - name: Show Clock Date
      dconf: key="/org/gnome/desktop/interface/clock-show-date" value="'true'"
    - name: Disable Lock Screen
      dconf: key="/org/gnome/desktop/lockdown/disable-lock-screen" value="'true'"
    - name: Disable Screensaver
      dconf: key="/org/gnome/desktop/screensaver/idle-activation-enabled" value="'false'"
    - name: Show Clock Date
      dconf: key="/org/gnome/desktop/wm/preferences/button-layout" value="'appmenu:minimize,maximize,close'"

- name: Modify Gnome Extensions
  block:
    - name: Disable extensions
      shell: "gnome-extensions disable {{ item }}"
      with_items:
        - ProxySwitcher@flannaghan.com
        - apps-menu@gnome-shell-extensions.gcampax.github.com
        - auto-move-windows@gnome-shell-extensions.gcampax.github.com
        - dash-to-dock@micxgx.gmail.com
        - desktop-icons@csoriano
        - drive-menu@gnome-shell-extensions.gcampax.github.com
        - launch-new-instance@gnome-shell-extensions.gcampax.github.com
        - native-window-placement@gnome-shell-extensions.gcampax.github.com
        - places-menu@gnome-shell-extensions.gcampax.github.com
        - screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
        - user-theme@gnome-shell-extensions.gcampax.github.com
        - window-list@gnome-shell-extensions.gcampax.github.com
        - windowsNavigator@gnome-shell-extensions.gcampax.github.com
        - workspace-indicator@gnome-shell-extensions.gcampax.github.com
        - workspaces-to-dock@passingthru67.gmail.com
        - horizontal-workspaces@gnome-shell-extensions.gcampax.github.com
    - name: Enable extensions
      shell: "gnome-extensions enable {{ item }}"
      with_items:
        - EasyScreenCast@iacopodeenosee.gmail.com

- name: Add Key bindings
  block:
    - dconf: key="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.title }}/name" value="'{{ item.name }}'"
      with_items:
      - { title: "custom0", name: "Terminal"}
      - { title: "custom1", name: "Firefox"}
      - { title: "custom2", name: "Files"}
    - dconf: key="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.title }}/binding" value="'{{ item.binding }}'"
      with_items:
      - { title: "custom0", binding: "<Super>Return"}
      - { title: "custom1", binding: "<Super>i"}
      - { title: "custom2", binding: "<Super>e"}
    - dconf: key="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/{{ item.title }}/command" value="'{{ item.command }}'"
      with_items:
      - { title: "custom0", command: "gnome-terminal" }
      - { title: "custom1", command: "firefox" }
      - { title: "custom2", command: "nautilus" }
    - dconf: key="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings" value="['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']"

- name: Install zsh and theme
  block: 
    - name: Install zsh
      apt:
        pkg:
          - zsh
    - file:
        state: absent
        path: /root/.oh-my-zsh
    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    - name: Setup Agnoster
      replace:
        path: /root/.zshrc
        regexp: ZSH_THEME=.*$
        replace: ZSH_THEME="agnoster"

- name: Install tools
  include: tools.yml