---

- name: Install tools from repo
  apt:
    pkg:
      - metasploit-framework
      - burpsuite
      - openvas
      - xautomation
      - hashcat
      - mimikatz
      - samba
      - remmina
    
- name: Install Juypter Notebook
  block:
    - pip:
        executable: pip3
        name:
          - jupyterlab
          - bash_kernel
    - shell: python -m bash_kernel.install